version: '3.1'
services:
  backend:
    image: tungnd-be:lastest
    ports:
      - 3451:3451
    environment:
      - BACK_END_HOST=host.docker.internal
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=tungnd44
      - DB_TEST=Testing
      - DATABASE_NAME=E-maintenance-system
      - S3_URL=s3-stg09.fptcloud.net
      - S3_ENDPOINT=https://s3-stg09.fptcloud.net
      - ACCESS_KEY=xxxxxx
      - SECRET_KEY=xxxxx
      - BUCKET_NAME=xxxxx
      - SENDER_EMAIL=xxxxxx
      - SENDER_NAME=xxxxx
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - MAIL_PASSWORD=xxxxx
  frontend:
    image: tungnd-fe:lastest
    ports:
      - 80:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_USER=xxxx
      - MYSQL_PASSWORD=xxx
  adminer:
    image: adminer
    ports:
      - 8081:8080
